name: nolatech_challenge
description: "NOLATECH's Flutter challenge"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^8.1.5
  flutter_slidable: ^3.1.1
  flutter_svg: ^2.0.4
  flutter_gen: ^5.6.0
  fpdart: ^1.1.0
  get_it: ^7.2.0
  go_router: ^14.1.2
  injectable: 2.1.0
  intl: ^0.18.1
  objectbox: ^4.0.2
  objectbox_flutter_libs: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_gen_runner: ^5.6.0
  injectable_generator: 2.1.3
  melos: ^6.0.0
  objectbox_generator: ^4.0.2

flutter_gen:
  output: lib/shared/gen
  assets:
    outputs:
      package_parameter_enabled: false
  fonts:
    outputs:
      package_parameter_enabled: false
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
